name: bqopd_web
description: The bqopd fanzine platform - Jaspr Web App.
publish_to: none

environment:
  sdk: ^3.11.0

jaspr:
  mode: client

dependencies:
  jaspr: ^0.23.1
  jaspr_router: ^0.8.2
  bloc: ^8.1.4
  bqopd_core:
    path: ../../packages/bqopd_core

dev_dependencies:
  jaspr_builder: ^0.23.1
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.0
  lints: ^5.0.0