// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpzmZxAtpK7QcGpjuQH55F13FKEKTyHCQ',
    appId: '1:17060476719:web:9c7e201c50938561e2d3da',
    messagingSenderId: '17060476719',
    projectId: 'bqopd-9ce06',
    authDomain: 'bqopd-9ce06.firebaseapp.com',
    storageBucket: 'bqopd-9ce06.appspot.com',
    measurementId: 'G-83CTK9L3NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIPR_mAKZeTc3GRgvvaF9JNNebZHpLECQ',
    appId: '1:17060476719:android:a82e45697659ecc7e2d3da',
    messagingSenderId: '17060476719',
    projectId: 'bqopd-9ce06',
    storageBucket: 'bqopd-9ce06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeAREQAqETGe20iAeek7j3v3Rt7yUnEcM',
    appId: '1:17060476719:ios:4f2a3c2ffdc7ccb3e2d3da',
    messagingSenderId: '17060476719',
    projectId: 'bqopd-9ce06',
    storageBucket: 'bqopd-9ce06.appspot.com',
    iosBundleId: 'com.bqopd.bqopd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpzmZxAtpK7QcGpjuQH55F13FKEKTyHCQ',
    appId: '1:17060476719:web:8fc7aba15908ad30e2d3da',
    messagingSenderId: '17060476719',
    projectId: 'bqopd-9ce06',
    authDomain: 'bqopd-9ce06.firebaseapp.com',
    storageBucket: 'bqopd-9ce06.appspot.com',
    measurementId: 'G-FJJN9TTVLR',
  );
}
