name: jaspr_app
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.6.0 <4.0.0'

resolution: workspace

dependencies:
  jaspr: ^0.23.0
  jaspr_router: any
  # The Brain
  core_logic:
  # Firebase Web Support
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  # State Management for Jaspr
  jaspr_riverpod: ^0.4.5

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.4.19
  jaspr_builder: ^0.23.0
  lints: ^6.0.0

jaspr:
  mode: server